# Generated by Django 4.2.11 on 2025-06-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Prefer not to say', 'Prefer not to say')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='medical_condition',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Diabetes', 'Diabetes'), ('Hypertension', 'Hypertension'), ('Asthma', 'Asthma'), ('Allergy (Peanut)', 'Allergy (Peanut)'), ('Allergy (Lactose)', 'Allergy (Lactose)'), ('Heart Disease', 'Heart Disease'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='admin_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table=None,
        ),
    ]
