# Generated by Django 4.2.11 on 2025-06-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='medical_condition',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Diabetes', 'Diabetes'), ('Hypertension', 'Hypertension'), ('Asthma', 'Asthma'), ('Allergy (Peanut)', 'Allergy (Peanut)'), ('Lactose Intolerant', 'Lactose Intolerant'), ('Heart Disease', 'Heart Disease'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
